DATA FRAME III

In [1]:
import pandas as pd

In [195]:
df = pd.read_csv(r"pandas\pandas\jamesbond.csv")
df

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [3]:
df = df.set_index(keys="Film")
df

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [4]:
df = df.reset_index()
df

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [5]:
df = df.set_index(keys="Film")

In [6]:
df = df.reset_index()
df = df.set_index("Year")
df

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,,
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
1967,You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
1969,On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
1971,Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
1973,Live and Let Die,Roger Moore,Guy Hamilton,460.3,30.8,NaN
1974,The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,27.7,NaN
1977,The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
1979,Moonraker,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
1981,For Your Eyes Only,Roger Moore,John Glen,449.4,60.2,NaN
1983,Never Say Never Again,Sean Connery,Irvin Kershner,380.0,86.0,NaN
1983,Octopussy,Roger Moore,John Glen,373.8,53.9,7.8
1985,A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
1987,The Living Daylights,Timothy Dalton,John Glen,313.5,68.8,5.2
1989,Licence to Kill,Timothy Dalton,John Glen,250.9,56.7,7.9
1995,GoldenEye,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
1997,Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
1999,The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
2002,Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
2006,Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
2008,Quantum of Solace,Daniel Craig,Marc Forster,514.2,181.4,8.1
2012,Skyfall,Daniel Craig,Sam Mendes,943.5,170.2,14.5
2015,Spectre,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [7]:
df = df.reset_index()
df = df.set_index("Film")
df

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [8]:
df = df.sort_index()

In [9]:
df.loc["Goldfinger"]["Budget"]

18.6

In [10]:
df.loc["GoldenEye"]

Year                            1995
Actor                 Pierce Brosnan
Director             Martin Campbell
Box Office                     518.5
Budget                          76.9
Bond Actor Salary                5.1
Name: GoldenEye, dtype: object

In [11]:
df.loc["Casino Royale"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [12]:
df.loc["Diamonds Are Forever":"From Russia with love"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6

In [13]:
df.loc["GoldenEye":]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [14]:
df.loc[:"From Russia with love"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6

In [15]:
df.loc[["Die Another Day", "From Russia with Love"]]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6

In [16]:
df.loc["Casino Royale"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [17]:
df

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [18]:
df.iloc[0]
df.iloc[15]
df.iloc[[15, 20]]
df.iloc[4:8]
df.iloc[20:]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [19]:
df.iloc[:3]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [20]:
df = df.set_index(keys="Film")

KeyError: "None of ['Film'] are in the columns"

In [ ]:
df.sort_index(inplace=True)

In [ ]:
df.iloc[2]

Year                        1967
Actor                David Niven
Director              Ken Hughes
Box Office                 315.0
Budget                      85.0
Bond Actor Salary            NaN
Name: Casino Royale, dtype: object

In [ ]:
df.iloc[0]

Year                        1985
Actor                Roger Moore
Director               John Glen
Box Office                 275.2
Budget                      54.5
Bond Actor Salary            9.1
Name: A View to a Kill, dtype: object

In [ ]:
df.iloc[22:]
df.sort_values(by="Year", ascending=False)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6

In [21]:
df

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [32]:
df.loc["Moonraker", "Year"]
df.loc["Moonraker", "Director"]
df.loc["Moonraker", ["Director", "Box Office"]]
df.loc[["Moonraker", "From Russia with Love"], "Year":"Box Office"]

                       Year         Actor       Director  Box Office
Film
Moonraker              1979   Roger Moore  Lewis Gilbert       535.0
From Russia with Love  1963  Sean Connery  Terence Young       543.8

In [33]:
df.loc["Moonraker":, :"Director"]

                                 Year           Actor            Director
Film
Moonraker                        1979     Roger Moore       Lewis Gilbert
Never Say Never Again            1983    Sean Connery      Irvin Kershner
Octopussy                        1983     Roger Moore           John Glen
On Her Majesty's Secret Service  1969  George Lazenby       Peter R. Hunt
Quantum of Solace                2008    Daniel Craig        Marc Forster
Skyfall                          2012    Daniel Craig          Sam Mendes
Spectre                          2015    Daniel Craig          Sam Mendes
The Living Daylights             1987  Timothy Dalton           John Glen
The Man with the Golden Gun      1974     Roger Moore        Guy Hamilton
The Spy Who Loved Me             1977     Roger Moore       Lewis Gilbert
The World Is Not Enough          1999  Pierce Brosnan       Michael Apted
Thunderball                      1965    Sean Connery       Terence Young
Tomorrow Never Dies              1997  Pierce Brosnan  Roger Spottiswoode
You Only Live Twice              1967    Sean Connery       Lewis Gilbert

In [48]:
df.iloc[3:5,5]

Film
Diamonds Are Forever     5.8
Die Another Day         17.9
Name: Bond Actor Salary, dtype: float64

In [51]:
df.loc["Dr. No", "Actor"] = "Sir Sear Conray"

In [55]:
df.loc["Dr. No", "Actor"]
df.loc["Dr. No", ["Box Office", "Budget", "Bond Actor Salary"]] = df.loc["Dr. No", ["Box Office", "Budget", "Bond Actor Salary"]] * 1000000

In [56]:
df.loc["Dr. No", ["Box Office", "Budget", "Bond Actor Salary"]]

Box Office           448800000.0
Budget                 7000000.0
Bond Actor Salary       600000.0
Name: Dr. No, dtype: object

In [60]:
df = df.set_index(keys="Film")
df

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [62]:
df = df.sort_index()

In [65]:
actor_is_sean = df["Actor"] == "Sean Connery"

In [68]:
df.loc[actor_is_sean, "Actor"] = "Sir Sear Connery"

In [69]:
df

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sear Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sear Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sear Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sear Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sear Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sear Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sear Connery,Lewis Gilbert,514.2,59.9,4.4

In [73]:
df.rename(axis=0, mapper={"GoldenEye" : "Golden Eye", "The World Is Not Enough" : "Best Bond Movie" })

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sear Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sear Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sear Connery,Terence Young,543.8,12.6,1.6
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sear Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sear Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Best Bond Movie,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sear Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sear Connery,Lewis Gilbert,514.2,59.9,4.4

In [74]:
df.rename(index={"GoldenEye" : "Golden Eye", "The World Is Not Enough" : "Best Bond Movie" })

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sear Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sear Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sear Connery,Terence Young,543.8,12.6,1.6
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sear Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sear Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Best Bond Movie,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sear Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sear Connery,Lewis Gilbert,514.2,59.9,4.4

In [76]:
df.head(1)
df.rename(axis=1, mapper={"Year": "Release Date"})

,Release Date,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sear Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sear Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sear Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sear Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sear Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sear Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sear Connery,Lewis Gilbert,514.2,59.9,4.4

In [81]:
df.drop(labels="A View to a Kill")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sear Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sear Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sear Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sear Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sear Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sear Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sear Connery,Lewis Gilbert,514.2,59.9,4.4

In [84]:
df.drop(labels=["A View to a Kill", "From Russia with Love"])
df.drop(labels="Casino Royale")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Diamonds Are Forever,1971,Sir Sear Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sear Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sear Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sear Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sear Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sear Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sear Connery,Lewis Gilbert,514.2,59.9,4.4

In [88]:
df.drop("Box Office", axis=1)

,Year,Actor,Director,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,1985,Roger Moore,John Glen,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,85.0,NaN
Diamonds Are Forever,1971,Sir Sear Connery,Guy Hamilton,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,154.2,17.9
Dr. No,1962,Sir Sear Connery,Terence Young,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,60.2,NaN
From Russia with Love,1963,Sir Sear Connery,Terence Young,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,76.9,5.1
Goldfinger,1964,Sir Sear Connery,Guy Hamilton,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,91.5,NaN
Never Say Never Again,1983,Sir Sear Connery,Irvin Kershner,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,158.3,13.5
Thunderball,1965,Sir Sear Connery,Terence Young,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,133.9,10.0
You Only Live Twice,1967,Sir Sear Connery,Lewis Gilbert,59.9,4.4

In [89]:
actor = df.pop("Actor")

In [91]:
actor

Film
A View to a Kill                        Roger Moore
Casino Royale                          Daniel Craig
Casino Royale                           David Niven
Diamonds Are Forever               Sir Sear Connery
Die Another Day                      Pierce Brosnan
Dr. No                             Sir Sear Connery
For Your Eyes Only                      Roger Moore
From Russia with Love              Sir Sear Connery
GoldenEye                            Pierce Brosnan
Goldfinger                         Sir Sear Connery
Licence to Kill                      Timothy Dalton
Live and Let Die                        Roger Moore
Moonraker                               Roger Moore
Never Say Never Again              Sir Sear Connery
Octopussy                               Roger Moore
On Her Majesty's Secret Service      George Lazenby
Quantum of Solace                      Daniel Craig
Skyfall                                Daniel Craig
Spectre                                Daniel Craig
The Living Daylights                 Timothy Dalton
The Man with the Golden Gun             Roger Moore
The Spy Who Loved Me                    Roger Moore
The World Is Not Enough              Pierce Brosnan
Thunderball                        Sir Sear Connery
Tomorrow Never Dies                  Pierce Brosnan
You Only Live Twice                Sir Sear Connery
Name: Actor, dtype: object

In [95]:
del df["Director"]

In [97]:
df = df.set_index(keys="Film")

In [104]:
df.sample(frac=0.1)

                  Year         Actor  Box Office  Budget  Bond Actor Salary
Film
Dr. No            1962  Sean Connery       448.8     7.0                0.6
A View to a Kill  1985   Roger Moore       275.2    54.5                9.1
Casino Royale     1967   David Niven       315.0    85.0                NaN

In [107]:
df.sample(n=3, axis=1)

                                 Budget  Bond Actor Salary  Box Office
Film
Dr. No                              7.0                0.6       448.8
From Russia with Love              12.6                1.6       543.8
Goldfinger                         18.6                3.2       820.4
Thunderball                        41.9                4.7       848.1
Casino Royale                      85.0                NaN       315.0
You Only Live Twice                59.9                4.4       514.2
On Her Majesty's Secret Service    37.3                0.6       291.5
Diamonds Are Forever               34.7                5.8       442.5
Live and Let Die                   30.8                NaN       460.3
The Man with the Golden Gun        27.7                NaN       334.0
The Spy Who Loved Me               45.1                NaN       533.0
Moonraker                          91.5                NaN       535.0
For Your Eyes Only                 60.2                NaN       449.4
Never Say Never Again              86.0                NaN       380.0
Octopussy                          53.9                7.8       373.8
A View to a Kill                   54.5                9.1       275.2
The Living Daylights               68.8                5.2       313.5
Licence to Kill                    56.7                7.9       250.9
GoldenEye                          76.9                5.1       518.5
Tomorrow Never Dies               133.9               10.0       463.2
The World Is Not Enough           158.3               13.5       439.5
Die Another Day                   154.2               17.9       465.4
Casino Royale                     145.3                3.3       581.5
Quantum of Solace                 181.4                8.1       514.2
Skyfall                           170.2               14.5       943.5
Spectre                           206.3                NaN       726.7

In [115]:
df.sort_values(by="Box Office", ascending=False)

,Year,Actor,Box Office,Budget,Bond Actor Salary
Film,,,,,
Skyfall,2012,Daniel Craig,943.5,170.2,14.5
Thunderball,1965,Sean Connery,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,820.4,18.6,3.2
Spectre,2015,Daniel Craig,726.7,206.3,NaN
Casino Royale,2006,Daniel Craig,581.5,145.3,3.3
From Russia with Love,1963,Sean Connery,543.8,12.6,1.6
Moonraker,1979,Roger Moore,535.0,91.5,NaN
The Spy Who Loved Me,1977,Roger Moore,533.0,45.1,NaN
GoldenEye,1995,Pierce Brosnan,518.5,76.9,5.1
You Only Live Twice,1967,Sean Connery,514.2,59.9,4.4
Quantum of Solace,2008,Daniel Craig,514.2,181.4,8.1
Die Another Day,2002,Pierce Brosnan,465.4,154.2,17.9
Tomorrow Never Dies,1997,Pierce Brosnan,463.2,133.9,10.0
Live and Let Die,1973,Roger Moore,460.3,30.8,NaN
For Your Eyes Only,1981,Roger Moore,449.4,60.2,NaN
Dr. No,1962,Sean Connery,448.8,7.0,0.6
Diamonds Are Forever,1971,Sean Connery,442.5,34.7,5.8
The World Is Not Enough,1999,Pierce Brosnan,439.5,158.3,13.5
Never Say Never Again,1983,Sean Connery,380.0,86.0,NaN
Octopussy,1983,Roger Moore,373.8,53.9,7.8
The Man with the Golden Gun,1974,Roger Moore,334.0,27.7,NaN
Casino Royale,1967,David Niven,315.0,85.0,NaN
The Living Daylights,1987,Timothy Dalton,313.5,68.8,5.2
On Her Majesty's Secret Service,1969,George Lazenby,291.5,37.3,0.6
A View to a Kill,1985,Roger Moore,275.2,54.5,9.1
Licence to Kill,1989,Timothy Dalton,250.9,56.7,7.9

In [118]:
df.nlargest(n=3, columns="Box Office")
df.nsmallest(n=2, columns="Box Office")

                  Year           Actor  Box Office  Budget  Bond Actor Salary
Film
Licence to Kill   1989  Timothy Dalton       250.9    56.7                7.9
A View to a Kill  1985     Roger Moore       275.2    54.5                9.1

In [120]:
df.nlargest(n=3, columns="Budget")

                   Year         Actor  Box Office  Budget  Bond Actor Salary
Film
Spectre            2015  Daniel Craig       726.7   206.3                NaN
Quantum of Solace  2008  Daniel Craig       514.2   181.4                8.1
Skyfall            2012  Daniel Craig       943.5   170.2               14.5

In [121]:
df.nsmallest(n=6, columns="Bond Actor Salary")

,Year,Actor,Box Office,Budget,Bond Actor Salary
Film,,,,,
Dr. No,1962,Sean Connery,448.8,7.0,0.6
On Her Majesty's Secret Service,1969,George Lazenby,291.5,37.3,0.6
From Russia with Love,1963,Sean Connery,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,820.4,18.6,3.2
Casino Royale,2006,Daniel Craig,581.5,145.3,3.3
You Only Live Twice,1967,Sean Connery,514.2,59.9,4.4

In [123]:
df["Box Office"].nlargest(6)
df["Year"].nsmallest(2)

Film
Dr. No                   1962
From Russia with Love    1963
Name: Year, dtype: int64

In [126]:
df = df.sort_index()
mask = df["Actor"] == "Sean Connery"

In [130]:
df.where(mask)

,Year,Actor,Box Office,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,1971.0,Sean Connery,442.5,34.7,5.8
Die Another Day,NaN,NaN,NaN,NaN,NaN
Dr. No,1962.0,Sean Connery,448.8,7.0,0.6
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN
From Russia with Love,1963.0,Sean Connery,543.8,12.6,1.6
GoldenEye,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,1983.0,Sean Connery,380.0,86.0,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,1967.0,Sean Connery,514.2,59.9,4.4

In [141]:
df = df.set_index(keys="Film")

In [142]:
df

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [143]:
df.columns = [x.replace(" ", "_") for x in df.columns]

In [146]:
df.query('Director == "Terence Young"')

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7

In [148]:
df.query("Box_Office > 500" )

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [149]:
df.query("Actor == 'Roger Moore' and Director == 'John Glen'")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1

In [131]:
mask = df["Box Office"] > 800
df.where(mask)

,Year,Actor,Box Office,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,NaN,NaN,NaN,NaN,NaN
Die Another Day,NaN,NaN,NaN,NaN,NaN
Dr. No,NaN,NaN,NaN,NaN,NaN
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN
From Russia with Love,NaN,NaN,NaN,NaN,NaN
GoldenEye,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,NaN,NaN,NaN,NaN,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN
Skyfall,2012.0,Daniel Craig,943.5,170.2,14.5
Spectre,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,NaN,NaN,NaN,NaN,NaN

In [133]:
col = []
for x in df.columns:
    col.append(x.replace(" ", "_"))
df.columns = col

In [135]:
df.query('Actor == "Sean Connery"')

,Year,Actor,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,
Diamonds Are Forever,1971,Sean Connery,442.5,34.7,5.8
Dr. No,1962,Sean Connery,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,820.4,18.6,3.2
Never Say Never Again,1983,Sean Connery,380.0,86.0,NaN
Thunderball,1965,Sean Connery,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,514.2,59.9,4.4

In [136]:
df.query('Director == "Terence Young"')

UndefinedVariableError: name 'Director' is not defined

In [137]:
df

,Year,Actor,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,
A View to a Kill,1985,Roger Moore,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,581.5,145.3,3.3
Casino Royale,1967,David Niven,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,465.4,154.2,17.9
Dr. No,1962,Sean Connery,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,460.3,30.8,NaN
Moonraker,1979,Roger Moore,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,380.0,86.0,NaN
Octopussy,1983,Roger Moore,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,943.5,170.2,14.5
Spectre,2015,Daniel Craig,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,439.5,158.3,13.5
Thunderball,1965,Sean Connery,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,514.2,59.9,4.4

In [150]:
df.query("Actor in ['Sean Connery', 'Timothy Dalton']")

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9

In [154]:
df["Director"].value_counts()["John Glen"]

5

In [168]:

df = df.sort_index()
df

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [172]:
def f(x):
    return str(x) + " millions"
df["Budget"].apply(f)

Film
A View to a Kill                    54.5 millions
Casino Royale                      145.3 millions
Casino Royale                       85.0 millions
Diamonds Are Forever                34.7 millions
Die Another Day                    154.2 millions
Dr. No                               7.0 millions
For Your Eyes Only                  60.2 millions
From Russia with Love               12.6 millions
GoldenEye                           76.9 millions
Goldfinger                          18.6 millions
Licence to Kill                     56.7 millions
Live and Let Die                    30.8 millions
Moonraker                           91.5 millions
Never Say Never Again               86.0 millions
Octopussy                           53.9 millions
On Her Majesty's Secret Service     37.3 millions
Quantum of Solace                  181.4 millions
Skyfall                            170.2 millions
Spectre                            206.3 millions
The Living Daylights                68.8 millions
The Man with the Golden Gun         27.7 millions
The Spy Who Loved Me                45.1 millions
The World Is Not Enough            158.3 millions
Thunderball                         41.9 millions
Tomorrow Never Dies                133.9 millions
You Only Live Twice                 59.9 millions
Name: Budget, dtype: object

In [173]:
col = ["Box Office", "Budget", "Bond Actor Salary"]
for x in col:
    df[x] = df[x].apply(f)
df

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2 millions,54.5 millions,9.1 millions
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5 millions,145.3 millions,3.3 millions
Casino Royale,1967,David Niven,Ken Hughes,315.0 millions,85.0 millions,nan millions
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5 millions,34.7 millions,5.8 millions
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4 millions,154.2 millions,17.9 millions
Dr. No,1962,Sean Connery,Terence Young,448.8 millions,7.0 millions,0.6 millions
For Your Eyes Only,1981,Roger Moore,John Glen,449.4 millions,60.2 millions,nan millions
From Russia with Love,1963,Sean Connery,Terence Young,543.8 millions,12.6 millions,1.6 millions
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5 millions,76.9 millions,5.1 millions
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4 millions,18.6 millions,3.2 millions
Licence to Kill,1989,Timothy Dalton,John Glen,250.9 millions,56.7 millions,7.9 millions
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3 millions,30.8 millions,nan millions
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0 millions,91.5 millions,nan millions
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0 millions,86.0 millions,nan millions
Octopussy,1983,Roger Moore,John Glen,373.8 millions,53.9 millions,7.8 millions
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5 millions,37.3 millions,0.6 millions
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2 millions,181.4 millions,8.1 millions
Skyfall,2012,Daniel Craig,Sam Mendes,943.5 millions,170.2 millions,14.5 millions
Spectre,2015,Daniel Craig,Sam Mendes,726.7 millions,206.3 millions,nan millions
The Living Daylights,1987,Timothy Dalton,John Glen,313.5 millions,68.8 millions,5.2 millions
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0 millions,27.7 millions,nan millions
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0 millions,45.1 millions,nan millions
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5 millions,158.3 millions,13.5 millions
Thunderball,1965,Sean Connery,Terence Young,848.1 millions,41.9 millions,4.7 millions
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2 millions,133.9 millions,10.0 millions
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2 millions,59.9 millions,4.4 millions

In [175]:
def good_movie(row):
    actor = row[1]
    budget = row[4]
    if actor == "Pierce Brosnan":
        return "The best"
    elif actor == "Roger Moore" and budget > 40:
        return "Enjoyable"
    return "idk lol"

In [180]:
df.apply(good_movie, axis=1)

Film
A View to a Kill                   Enjoyable
Casino Royale                        idk lol
Casino Royale                        idk lol
Diamonds Are Forever                 idk lol
Die Another Day                     The best
Dr. No                               idk lol
For Your Eyes Only                 Enjoyable
From Russia with Love                idk lol
GoldenEye                           The best
Goldfinger                           idk lol
Licence to Kill                      idk lol
Live and Let Die                     idk lol
Moonraker                          Enjoyable
Never Say Never Again                idk lol
Octopussy                          Enjoyable
On Her Majesty's Secret Service      idk lol
Quantum of Solace                    idk lol
Skyfall                              idk lol
Spectre                              idk lol
The Living Daylights                 idk lol
The Man with the Golden Gun          idk lol
The Spy Who Loved Me               Enjoyable
The World Is Not Enough             The best
Thunderball                          idk lol
Tomorrow Never Dies                 The best
You Only Live Twice                  idk lol
dtype: object

In [182]:
def hala(x):
    if x[0] in range(1900, 2300):
        return "Jej"
    return "LOL"
df.apply(hala)

Year                 Jej
Actor                LOL
Director             LOL
Box Office           LOL
Budget               LOL
Bond Actor Salary    LOL
dtype: object

In [186]:
s = df["Director"]

In [185]:
.head(3)

NameError: name 's' is not defined

In [188]:
s[0] = "LOL"

C:\Users\informatika\AppData\Local\Temp\ipykernel_5956\2950587790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s[0] = "LOL"

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,LOL,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [192]:
df = df.set_index("Film").sort_index()
s = df["Director"].

In [194]:
s[0] = "LOL"

C:\Users\informatika\AppData\Local\Temp\ipykernel_5956\2950587790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s[0] = "LOL"

In [197]:
df = df.set_index("Film").sort_index()
s = df["Director"].copy()
s

Film
A View to a Kill                            John Glen
Casino Royale                         Martin Campbell
Casino Royale                              Ken Hughes
Diamonds Are Forever                     Guy Hamilton
Die Another Day                          Lee Tamahori
Dr. No                                  Terence Young
For Your Eyes Only                          John Glen
From Russia with Love                   Terence Young
GoldenEye                             Martin Campbell
Goldfinger                               Guy Hamilton
Licence to Kill                             John Glen
Live and Let Die                         Guy Hamilton
Moonraker                               Lewis Gilbert
Never Say Never Again                  Irvin Kershner
Octopussy                                   John Glen
On Her Majesty's Secret Service         Peter R. Hunt
Quantum of Solace                        Marc Forster
Skyfall                                    Sam Mendes
Spectre                                    Sam Mendes
The Living Daylights                        John Glen
The Man with the Golden Gun              Guy Hamilton
The Spy Who Loved Me                    Lewis Gilbert
The World Is Not Enough                 Michael Apted
Thunderball                             Terence Young
Tomorrow Never Dies                Roger Spottiswoode
You Only Live Twice                     Lewis Gilbert
Name: Director, dtype: object

In [198]:
s[0] = "LOL"
df

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4